###swagger 配置
#server:
#  port: 9001
#  tomcat:
#    uri-encoding: UTF-8
#    max-threads: 800
#    min-spare-threads: 30
#    max-connections: 10000
#
#
#spring:#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
#swagger2:
#  enable: true
#
